package mongodb_test;

import com.mongodb.BasicDBObject;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.Updates;
import java.util.Iterator;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author masterx
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    MongoClientURI uri;
    MongoClient client;
    MongoDatabase db;

    public principal() {
        uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");
        client = new MongoClient(uri);
        db = client.getDatabase(uri.getDatabase());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Empleados = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt_codAgregarEmpleados = new javax.swing.JTextField();
        jt_pNombreAgregarEmpleado = new javax.swing.JTextField();
        jt_sNombreAgregarEmpleado = new javax.swing.JTextField();
        jt_pApellidoAgregarEmpleado = new javax.swing.JTextField();
        jt_sApellidoAgregarEmpleado = new javax.swing.JTextField();
        jt_cargoAgregarEmpleado = new javax.swing.JTextField();
        bt_agregarEmpleado = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jt_codModificarEmpleados = new javax.swing.JTextField();
        bt_modificarEmpleado = new javax.swing.JButton();
        jt_pNombreModificarEmpleado = new javax.swing.JTextField();
        jt_sNombreModificarEmpleado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jt_pApellidoModificarEmpleado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jt_sApellidoModificarEmpleado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jt_cargoModificarEmpleado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bt_buscarModificarEmpleado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cb_eliminarEmpleados = new javax.swing.JComboBox<>();
        bt_eliminarEmpleados = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cb_veterinarios = new javax.swing.JComboBox<>();
        cb_animales = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new javax.swing.JTextArea();
        cb_dosis = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        bt_enviarDosis = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        tf_porcion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tf_codDieta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bt_entrarPersonal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_entrarAnimales = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bt_entrarZoologico = new javax.swing.JButton();

        jLabel5.setText("Codigo del empleado:");

        jLabel6.setText("Primer nombre:");

        jLabel7.setText("Segundo nombre:");

        jLabel8.setText("Primer apellido:");

        jLabel9.setText("Segundo apellido:");

        jLabel10.setText("Cargo:");

        bt_agregarEmpleado.setText("Agregar");
        bt_agregarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarEmpleadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_codAgregarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_pNombreAgregarEmpleado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_sNombreAgregarEmpleado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_pApellidoAgregarEmpleado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_sApellidoAgregarEmpleado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_cargoAgregarEmpleado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_agregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_agregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jt_codAgregarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jt_pNombreAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jt_sNombreAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jt_pApellidoAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jt_sApellidoAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jt_cargoAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Empleados", jPanel1);

        jLabel11.setText("Codigo del empleado:");

        bt_modificarEmpleado.setText("Modificar");
        bt_modificarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificarEmpleadoMouseClicked(evt);
            }
        });
        bt_modificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarEmpleadoActionPerformed(evt);
            }
        });

        jLabel12.setText("Segundo nombre:");

        jLabel13.setText("Primer apellido:");

        jLabel14.setText("Segundo apellido:");

        jLabel15.setText("Cargo:");

        jLabel16.setText("Primer nombre:");

        bt_buscarModificarEmpleado.setText("Buscar");
        bt_buscarModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarModificarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_codModificarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_pNombreModificarEmpleado))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_sNombreModificarEmpleado))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_pApellidoModificarEmpleado))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_sApellidoModificarEmpleado))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_cargoModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_modificarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(bt_buscarModificarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jt_codModificarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_buscarModificarEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_pNombreModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jt_sNombreModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jt_pApellidoModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jt_sApellidoModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt_cargoModificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addComponent(bt_modificarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Modificar Empleados", jPanel3);

        bt_eliminarEmpleados.setText("Eliminar");
        bt_eliminarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 249, Short.MAX_VALUE)
                        .addComponent(bt_eliminarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_eliminarEmpleados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_eliminarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(bt_eliminarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Eliminar Empleados", jPanel2);

        cb_animales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_animalesActionPerformed(evt);
            }
        });

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_descripcion);

        cb_dosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_dosisActionPerformed(evt);
            }
        });

        jLabel17.setText("Veterinario:");

        jLabel18.setText("Dosis:");

        jLabel19.setText("Animal:");

        bt_enviarDosis.setText("Enviar");
        bt_enviarDosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarDosisActionPerformed(evt);
            }
        });

        jLabel20.setText("Tamaño:");

        jLabel21.setText("Codigo Dieta:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(cb_veterinarios, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(cb_dosis, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_enviarDosis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_animales, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(0, 19, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_porcion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_codDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_veterinarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_dosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_animales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_porcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(tf_codDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(bt_enviarDosis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dietas", jPanel4);

        javax.swing.GroupLayout jd_EmpleadosLayout = new javax.swing.GroupLayout(jd_Empleados.getContentPane());
        jd_Empleados.getContentPane().setLayout(jd_EmpleadosLayout);
        jd_EmpleadosLayout.setHorizontalGroup(
            jd_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jd_EmpleadosLayout.setVerticalGroup(
            jd_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Sistema de Mantenimiento del Zoologico de Cordoba");

        bt_entrarPersonal.setText("Entrar");
        bt_entrarPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_entrarPersonalMouseClicked(evt);
            }
        });
        bt_entrarPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarPersonalActionPerformed(evt);
            }
        });

        jLabel2.setText("Personal:");

        jLabel3.setText("Animales:");

        bt_entrarAnimales.setText("Entrar");

        jLabel4.setText("Zoologico:");

        bt_entrarZoologico.setText("Entrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_entrarPersonal)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bt_entrarZoologico, javax.swing.GroupLayout.PREFERRED_SIZE, 62, Short.MAX_VALUE)
                                .addComponent(bt_entrarAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bt_entrarPersonal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bt_entrarAnimales))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bt_entrarZoologico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_entrarPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_entrarPersonalMouseClicked

    }//GEN-LAST:event_bt_entrarPersonalMouseClicked

    private void bt_agregarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarEmpleadoMouseClicked
        String id, pNombre, sNombre, pApellido, sApellido, cargo;
        try {
            id = this.jt_codAgregarEmpleados.getText();
            pNombre = this.jt_pNombreAgregarEmpleado.getText();
            sNombre = this.jt_sNombreAgregarEmpleado.getText();
            pApellido = this.jt_pApellidoAgregarEmpleado.getText();
            sApellido = this.jt_sApellidoAgregarEmpleado.getText();
            cargo = this.jt_cargoAgregarEmpleado.getText();
            Document doc = new Document();
            doc.append("CodigoEmpleado", id);
            doc.append("PrimerNombre", pNombre);
            doc.append("SegundoNombre", sNombre);
            doc.append("PrimerApellido", pApellido);
            doc.append("SegundoApellido", sApellido);
            doc.append("Cargo", cargo);
            if ("Veterinario".equals(cargo)) {
                Document docNuevo = new Document();
                docNuevo.append("CodigoVeterinario", id);
                db.getCollection("Veterinarios").insertOne(docNuevo);
            }
            if ("Mantenimiento".equals(cargo)) {
                Document docNuevo = new Document();
                docNuevo.append("CodigoEmpleado", id);
                db.getCollection("PersonalMantenimiento").insertOne(docNuevo);
            }
            if ("Cuidador".equals(cargo)) {
                Document docNuevo = new Document();
                docNuevo.append("CodigoEmpleado", id);
                db.getCollection("Cuidadores").insertOne(docNuevo);
            }
            db.getCollection("Empleados").insertOne(doc);
            JOptionPane.showMessageDialog(this.jd_Empleados, "Agregado Exitosamente!");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_agregarEmpleadoMouseClicked

    private void bt_entrarPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarPersonalActionPerformed
        this.jd_Empleados.setResizable(false);
        this.jd_Empleados.setLocationRelativeTo(this);
        this.jd_Empleados.pack();
        this.jd_Empleados.setVisible(true);
        ComboBoxModel model = this.cb_eliminarEmpleados.getModel();
        FindIterable<Document> iterDoc = db.getCollection("Empleados").find();
        int i = 1;
        for (Document doc : iterDoc) {
            this.cb_eliminarEmpleados.addItem((String) doc.get("CodigoEmpleado"));
            i++;
        }
        int j = 1;
        FindIterable<Document> iterDoc2 = db.getCollection("Veterinarios").find();
        for (Document doc : iterDoc2) {
            this.cb_veterinarios.addItem((String) doc.get("CodigoVeterinario"));
            j++;
        }
        FindIterable<Document> iterDoc3 = db.getCollection("Animales").find();
        int k = 1;
        for (Document doc : iterDoc3) {
            this.cb_animales.addItem((String) doc.get("CodigoAnimal"));
            j++;
        }


    }//GEN-LAST:event_bt_entrarPersonalActionPerformed

    private void bt_modificarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificarEmpleadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_modificarEmpleadoMouseClicked

    private void bt_buscarModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarModificarEmpleadoActionPerformed
        String codEmpleado;
        try {
            codEmpleado = this.jt_codModificarEmpleados.getText();
            BasicDBObject query = new BasicDBObject();
            query.put("CodigoEmpleado", codEmpleado);
            System.out.println();
            Document doc = db.getCollection("Empleados").find(query).first();
            this.jt_pNombreModificarEmpleado.setText((String) doc.get("PrimerNombre"));
            this.jt_sNombreModificarEmpleado.setText((String) doc.get("SegundoNombre"));
            this.jt_pApellidoModificarEmpleado.setText((String) doc.get("PrimerApellido"));
            this.jt_sApellidoModificarEmpleado.setText((String) doc.get("SegundoApellido"));
            this.jt_cargoModificarEmpleado.setText((String) doc.get("Cargo"));
            JOptionPane.showMessageDialog(this.jd_Empleados, "Encontrado!");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_bt_buscarModificarEmpleadoActionPerformed

    private void bt_modificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarEmpleadoActionPerformed
        String codEmpleado = this.jt_codModificarEmpleados.getText();
        String pNombre, sNombre, pApellido, sApellido, cargo;
        try {
            pNombre = this.jt_pNombreModificarEmpleado.getText();
            sNombre = this.jt_sNombreModificarEmpleado.getText();
            pApellido = this.jt_pApellidoModificarEmpleado.getText();
            sApellido = this.jt_sApellidoModificarEmpleado.getText();
            cargo = this.jt_cargoModificarEmpleado.getText();
            db.getCollection("Empleados").updateOne(Filters.eq("CodigoEmpleado", codEmpleado), Updates.set("PrimerNombre", pNombre));
            db.getCollection("Empleados").updateOne(Filters.eq("CodigoEmpleado", codEmpleado), Updates.set("SegundoNombre", sNombre));
            db.getCollection("Empleados").updateOne(Filters.eq("CodigoEmpleado", codEmpleado), Updates.set("PrimerApellido", pApellido));
            db.getCollection("Empleados").updateOne(Filters.eq("CodigoEmpleado", codEmpleado), Updates.set("SegundoApellido", sApellido));
            db.getCollection("Empleados").updateOne(Filters.eq("CodigoEmpleado", codEmpleado), Updates.set("Cargo", cargo));
            JOptionPane.showMessageDialog(this.jd_Empleados, "Modificado Exitosamente!");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_bt_modificarEmpleadoActionPerformed

    private void bt_eliminarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarEmpleadosActionPerformed
        String codEmpleado = this.cb_eliminarEmpleados.getSelectedItem().toString();
        int opcion;
        try {
            opcion = JOptionPane.showConfirmDialog(this.jd_Empleados, "¿Desea Borrarlo?", "Borrar", YES_NO_OPTION);
            if (opcion == 0) {
                db.getCollection("Empleados").deleteOne(Filters.eq("CodigoEmpleado", codEmpleado));
                JOptionPane.showMessageDialog(this.jd_Empleados, "Eliminado!");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_eliminarEmpleadosActionPerformed

    private void cb_dosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_dosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_dosisActionPerformed

    private void cb_animalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_animalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_animalesActionPerformed

    private void bt_enviarDosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarDosisActionPerformed
        String idVet;
        String dosis;
        String idAnimal;
        String descripcion;
        String porcion;
        try {
            idVet = this.cb_veterinarios.getSelectedItem().toString();
            dosis = this.cb_dosis.getSelectedItem().toString();
            idAnimal = this.cb_animales.getSelectedItem().toString();
            descripcion = this.ta_descripcion.getText();
            porcion = this.tf_porcion.getText();
            Document doc = new Document();
            doc.append("CodigoDieta", this.tf_codDieta.getText());
            doc.append("CodigoVeterinario", idVet);
            doc.append("VecesAlDia", dosis);
            doc.append("Descripcion", descripcion);
            doc.append("Porcion", porcion);
            db.getCollection("Dietas").insertOne(doc);
            JOptionPane.showMessageDialog(this.jd_Empleados, "Agregado!");
        } catch (Exception e) {
        }

    }//GEN-LAST:event_bt_enviarDosisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregarEmpleado;
    private javax.swing.JButton bt_buscarModificarEmpleado;
    private javax.swing.JButton bt_eliminarEmpleados;
    private javax.swing.JButton bt_entrarAnimales;
    private javax.swing.JButton bt_entrarPersonal;
    private javax.swing.JButton bt_entrarZoologico;
    private javax.swing.JButton bt_enviarDosis;
    private javax.swing.JButton bt_modificarEmpleado;
    private javax.swing.JComboBox<String> cb_animales;
    private javax.swing.JComboBox<String> cb_dosis;
    private javax.swing.JComboBox<String> cb_eliminarEmpleados;
    private javax.swing.JComboBox<String> cb_veterinarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jd_Empleados;
    private javax.swing.JTextField jt_cargoAgregarEmpleado;
    private javax.swing.JTextField jt_cargoModificarEmpleado;
    private javax.swing.JTextField jt_codAgregarEmpleados;
    private javax.swing.JTextField jt_codModificarEmpleados;
    private javax.swing.JTextField jt_pApellidoAgregarEmpleado;
    private javax.swing.JTextField jt_pApellidoModificarEmpleado;
    private javax.swing.JTextField jt_pNombreAgregarEmpleado;
    private javax.swing.JTextField jt_pNombreModificarEmpleado;
    private javax.swing.JTextField jt_sApellidoAgregarEmpleado;
    private javax.swing.JTextField jt_sApellidoModificarEmpleado;
    private javax.swing.JTextField jt_sNombreAgregarEmpleado;
    private javax.swing.JTextField jt_sNombreModificarEmpleado;
    private javax.swing.JTextArea ta_descripcion;
    private javax.swing.JTextField tf_codDieta;
    private javax.swing.JTextField tf_porcion;
    // End of variables declaration//GEN-END:variables
}
