package mongodb_test;

import com.mongodb.BasicDBObject;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import com.mongodb.client.model.Updates;
import java.rmi.UnknownHostException;
import java.util.Iterator;
import java.util.Scanner;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author masterx
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    MongoClientURI uri;
    MongoClient client;
    MongoDatabase db;

    public principal() {
        uri = new MongoClientURI("mongodb://admin:admin@ds044709.mlab.com:44709/proyectoz");

        client = new MongoClient(uri);

        db = client.getDatabase(uri.getDatabase());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Zona = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jb_CrearZona = new javax.swing.JButton();
        jb_modificarZonas = new javax.swing.JButton();
        jb_eliminarzonas = new javax.swing.JButton();
        VentanaZoologico = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        Jb_VentanaZona = new javax.swing.JButton();
        jb_VentanaHabitat = new javax.swing.JButton();
        jb_VentanaDependencia = new javax.swing.JButton();
        jd_eliminarZona = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        cb_EliminarZona = new javax.swing.JComboBox<>();
        jb_eliminarZona = new javax.swing.JButton();
        jd_modifcarzona = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jb_ModificarZona = new javax.swing.JButton();
        jt_BuscarModificarZ = new javax.swing.JTextField();
        jb_buscarModificarZ = new javax.swing.JButton();
        jlzona3 = new javax.swing.JLabel();
        jl_idModificarZ = new javax.swing.JLabel();
        jlzona5 = new javax.swing.JLabel();
        jt_nombreModificarZona = new javax.swing.JTextField();
        jd_crearzona = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jlzona = new javax.swing.JLabel();
        jlzona1 = new javax.swing.JLabel();
        jt_codigozona = new javax.swing.JTextField();
        jt_nombrezona = new javax.swing.JTextField();
        jb_crearZ = new javax.swing.JButton();
        jd_Habitats = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jd_VentanaCrearHbitat = new javax.swing.JButton();
        JB_VentatnaEliminarHabitat = new javax.swing.JButton();
        jb_VentanaModificarHabitat = new javax.swing.JButton();
        Jd_CrearHabitat = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        cb_zonacrearhabitat = new javax.swing.JComboBox<>();
        jt_CodigoHabitat = new javax.swing.JTextField();
        Jt_NombreHabitat = new javax.swing.JTextField();
        jb_crearhabitat = new javax.swing.JButton();
        jlzona8 = new javax.swing.JLabel();
        jlzona9 = new javax.swing.JLabel();
        jlzona10 = new javax.swing.JLabel();
        jd_ModificarHabitat = new javax.swing.JDialog();
        jb_buscarhabitat = new javax.swing.JButton();
        jt_BuscarModHabitat = new javax.swing.JTextField();
        jb_ModificarHabitat = new javax.swing.JButton();
        jlzona11 = new javax.swing.JLabel();
        jt_ModNombreHabitat = new javax.swing.JTextField();
        jl_codigohabitat = new javax.swing.JLabel();
        jlzona12 = new javax.swing.JLabel();
        jl_zonahabitat = new javax.swing.JLabel();
        jlzona13 = new javax.swing.JLabel();
        jd_EliminarHabitat = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        cb_eliminarHabitat = new javax.swing.JComboBox<>();
        jb_eliminarHabitat = new javax.swing.JButton();
        JD_Dependencias = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jb_VtcrearDependenica = new javax.swing.JButton();
        jb_VTModDependencia = new javax.swing.JButton();
        jb_VTEliminarDependencia = new javax.swing.JButton();
        Jd_crearDependencia = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jldep = new javax.swing.JLabel();
        jt_CodigoDependencia = new javax.swing.JTextField();
        jldep1 = new javax.swing.JLabel();
        jt_NombreDependencia = new javax.swing.JTextField();
        jldep2 = new javax.swing.JLabel();
        cb_zonaDependencia = new javax.swing.JComboBox<>();
        jb_CrearDependencia = new javax.swing.JButton();
        jd_eliminarDependencia = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        cb_eliminarDempendencia = new javax.swing.JComboBox<>();
        jb_EliminarDependencia = new javax.swing.JButton();
        JD_ModificarDependencia = new javax.swing.JDialog();
        jPanel12 = new javax.swing.JPanel();
        jt_idDependencia = new javax.swing.JTextField();
        jldep3 = new javax.swing.JLabel();
        jl_zonadependencia = new javax.swing.JLabel();
        jldep4 = new javax.swing.JLabel();
        jl_codigodependencia = new javax.swing.JLabel();
        jldep5 = new javax.swing.JLabel();
        jt_ModNombreDependencia = new javax.swing.JTextField();
        jb_BuscarDependencia = new javax.swing.JButton();
        jb_ModDepencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_entrarPersonal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_entrarAnimales = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bt_entrarZoologico = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jb_CrearZona.setBackground(new java.awt.Color(0, 204, 153));
        jb_CrearZona.setText("Crear");
        jb_CrearZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_CrearZonaActionPerformed(evt);
            }
        });

        jb_modificarZonas.setText("Modificar");
        jb_modificarZonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarZonasActionPerformed(evt);
            }
        });

        jb_eliminarzonas.setText("Eliminar");
        jb_eliminarzonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarzonasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_CrearZona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_modificarZonas, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jb_eliminarzonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jb_CrearZona)
                .addGap(35, 35, 35)
                .addComponent(jb_modificarZonas)
                .addGap(38, 38, 38)
                .addComponent(jb_eliminarzonas)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_ZonaLayout = new javax.swing.GroupLayout(jd_Zona.getContentPane());
        jd_Zona.getContentPane().setLayout(jd_ZonaLayout);
        jd_ZonaLayout.setHorizontalGroup(
            jd_ZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_ZonaLayout.setVerticalGroup(
            jd_ZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Jb_VentanaZona.setText("Zona");
        Jb_VentanaZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jb_VentanaZonaActionPerformed(evt);
            }
        });

        jb_VentanaHabitat.setText("Habitat");
        jb_VentanaHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_VentanaHabitatActionPerformed(evt);
            }
        });

        jb_VentanaDependencia.setText("Dependencia");
        jb_VentanaDependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_VentanaDependenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jb_VentanaZona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_VentanaDependencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_VentanaHabitat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Jb_VentanaZona)
                .addGap(44, 44, 44)
                .addComponent(jb_VentanaDependencia)
                .addGap(35, 35, 35)
                .addComponent(jb_VentanaHabitat)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VentanaZoologicoLayout = new javax.swing.GroupLayout(VentanaZoologico.getContentPane());
        VentanaZoologico.getContentPane().setLayout(VentanaZoologicoLayout);
        VentanaZoologicoLayout.setHorizontalGroup(
            VentanaZoologicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaZoologicoLayout.setVerticalGroup(
            VentanaZoologicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jb_eliminarZona.setText("Eliminar");
        jb_eliminarZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarZonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jb_eliminarZona, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(cb_EliminarZona, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(cb_EliminarZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jb_eliminarZona)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jd_eliminarZonaLayout = new javax.swing.GroupLayout(jd_eliminarZona.getContentPane());
        jd_eliminarZona.getContentPane().setLayout(jd_eliminarZonaLayout);
        jd_eliminarZonaLayout.setHorizontalGroup(
            jd_eliminarZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_eliminarZonaLayout.setVerticalGroup(
            jd_eliminarZonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jb_ModificarZona.setText("Modifcar");
        jb_ModificarZona.setEnabled(false);
        jb_ModificarZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ModificarZonaActionPerformed(evt);
            }
        });

        jt_BuscarModificarZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_BuscarModificarZActionPerformed(evt);
            }
        });

        jb_buscarModificarZ.setText("Buscar");
        jb_buscarModificarZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarModificarZActionPerformed(evt);
            }
        });

        jlzona3.setText("CodigoZona");

        jlzona5.setText("NombreZona");

        jt_nombreModificarZona.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jb_ModificarZona, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlzona3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlzona5)
                            .addComponent(jt_BuscarModificarZ, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_buscarModificarZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_idModificarZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jt_nombreModificarZona))
                        .addGap(76, 76, 76))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_BuscarModificarZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_buscarModificarZ))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlzona3)
                    .addComponent(jl_idModificarZ, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlzona5)
                    .addComponent(jt_nombreModificarZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jb_ModificarZona)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jd_modifcarzonaLayout = new javax.swing.GroupLayout(jd_modifcarzona.getContentPane());
        jd_modifcarzona.getContentPane().setLayout(jd_modifcarzonaLayout);
        jd_modifcarzonaLayout.setHorizontalGroup(
            jd_modifcarzonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_modifcarzonaLayout.setVerticalGroup(
            jd_modifcarzonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jlzona.setText("Codigo Zona: ");

        jlzona1.setText("Nombre Zona: ");

        jb_crearZ.setText("Crear");
        jb_crearZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearZActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlzona)
                            .addComponent(jlzona1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_codigozona, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jt_nombrezona)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jb_crearZ, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlzona)
                    .addComponent(jt_codigozona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlzona1)
                    .addComponent(jt_nombrezona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jb_crearZ)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jd_crearzonaLayout = new javax.swing.GroupLayout(jd_crearzona.getContentPane());
        jd_crearzona.getContentPane().setLayout(jd_crearzonaLayout);
        jd_crearzonaLayout.setHorizontalGroup(
            jd_crearzonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_crearzonaLayout.setVerticalGroup(
            jd_crearzonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jd_VentanaCrearHbitat.setText("Crear");
        jd_VentanaCrearHbitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jd_VentanaCrearHbitatActionPerformed(evt);
            }
        });

        JB_VentatnaEliminarHabitat.setText("Eliminar");
        JB_VentatnaEliminarHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_VentatnaEliminarHabitatActionPerformed(evt);
            }
        });

        jb_VentanaModificarHabitat.setText("Modificar");
        jb_VentanaModificarHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_VentanaModificarHabitatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_VentatnaEliminarHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jb_VentanaModificarHabitat, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addComponent(jd_VentanaCrearHbitat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jd_VentanaCrearHbitat)
                .addGap(42, 42, 42)
                .addComponent(jb_VentanaModificarHabitat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(JB_VentatnaEliminarHabitat)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout jd_HabitatsLayout = new javax.swing.GroupLayout(jd_Habitats.getContentPane());
        jd_Habitats.getContentPane().setLayout(jd_HabitatsLayout);
        jd_HabitatsLayout.setHorizontalGroup(
            jd_HabitatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_HabitatsLayout.setVerticalGroup(
            jd_HabitatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jb_crearhabitat.setText("Crear");
        jb_crearhabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearhabitatActionPerformed(evt);
            }
        });

        jlzona8.setText("Zona");

        jlzona9.setText("CodigoHabitat");

        jlzona10.setText("Nombre:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlzona8)
                            .addComponent(jlzona9)
                            .addComponent(jlzona10))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_zonacrearhabitat, 0, 173, Short.MAX_VALUE)
                            .addComponent(Jt_NombreHabitat)
                            .addComponent(jt_CodigoHabitat)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jb_crearhabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_zonacrearhabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlzona8))
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_CodigoHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlzona9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jt_NombreHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlzona10))
                .addGap(49, 49, 49)
                .addComponent(jb_crearhabitat)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout Jd_CrearHabitatLayout = new javax.swing.GroupLayout(Jd_CrearHabitat.getContentPane());
        Jd_CrearHabitat.getContentPane().setLayout(Jd_CrearHabitatLayout);
        Jd_CrearHabitatLayout.setHorizontalGroup(
            Jd_CrearHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Jd_CrearHabitatLayout.setVerticalGroup(
            Jd_CrearHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jb_buscarhabitat.setText("Buscar");
        jb_buscarhabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarhabitatActionPerformed(evt);
            }
        });

        jb_ModificarHabitat.setText("Modificar");
        jb_ModificarHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ModificarHabitatActionPerformed(evt);
            }
        });

        jlzona11.setText("CodigoHabitat");

        jlzona12.setText("Zona");

        jlzona13.setText("Nombre");

        javax.swing.GroupLayout jd_ModificarHabitatLayout = new javax.swing.GroupLayout(jd_ModificarHabitat.getContentPane());
        jd_ModificarHabitat.getContentPane().setLayout(jd_ModificarHabitatLayout);
        jd_ModificarHabitatLayout.setHorizontalGroup(
            jd_ModificarHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarHabitatLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jb_ModificarHabitat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_ModificarHabitatLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jd_ModificarHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ModificarHabitatLayout.createSequentialGroup()
                        .addComponent(jlzona12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_ModificarHabitatLayout.createSequentialGroup()
                        .addGroup(jd_ModificarHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlzona11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlzona13)
                            .addComponent(jt_BuscarModHabitat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jd_ModificarHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_buscarhabitat)
                            .addGroup(jd_ModificarHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jl_zonahabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jl_codigohabitat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jt_ModNombreHabitat, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)))
                        .addGap(76, 76, 76))))
        );
        jd_ModificarHabitatLayout.setVerticalGroup(
            jd_ModificarHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarHabitatLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jd_ModificarHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_buscarhabitat)
                    .addComponent(jt_BuscarModHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jd_ModificarHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ModificarHabitatLayout.createSequentialGroup()
                        .addComponent(jlzona11)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jl_codigohabitat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ModificarHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlzona12)
                    .addComponent(jl_zonahabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jd_ModificarHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_ModNombreHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlzona13))
                .addGap(30, 30, 30)
                .addComponent(jb_ModificarHabitat)
                .addGap(29, 29, 29))
        );

        jb_eliminarHabitat.setText("Eliminar");
        jb_eliminarHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarHabitatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_eliminarHabitat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_eliminarHabitat, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(cb_eliminarHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jb_eliminarHabitat)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout jd_EliminarHabitatLayout = new javax.swing.GroupLayout(jd_EliminarHabitat.getContentPane());
        jd_EliminarHabitat.getContentPane().setLayout(jd_EliminarHabitatLayout);
        jd_EliminarHabitatLayout.setHorizontalGroup(
            jd_EliminarHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_EliminarHabitatLayout.setVerticalGroup(
            jd_EliminarHabitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jb_VtcrearDependenica.setText("Crear");
        jb_VtcrearDependenica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_VtcrearDependenicaActionPerformed(evt);
            }
        });

        jb_VTModDependencia.setText("Modificar");
        jb_VTModDependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_VTModDependenciaActionPerformed(evt);
            }
        });

        jb_VTEliminarDependencia.setText("Eliminar");
        jb_VTEliminarDependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_VTEliminarDependenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_VTEliminarDependencia)
                    .addComponent(jb_VTModDependencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_VtcrearDependenica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jb_VtcrearDependenica)
                .addGap(42, 42, 42)
                .addComponent(jb_VTModDependencia)
                .addGap(50, 50, 50)
                .addComponent(jb_VTEliminarDependencia)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JD_DependenciasLayout = new javax.swing.GroupLayout(JD_Dependencias.getContentPane());
        JD_Dependencias.getContentPane().setLayout(JD_DependenciasLayout);
        JD_DependenciasLayout.setHorizontalGroup(
            JD_DependenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_DependenciasLayout.setVerticalGroup(
            JD_DependenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jldep.setText("CodigoDependencia");

        jldep1.setText("NombreDependencia");

        jldep2.setText("Zona");

        jb_CrearDependencia.setText("Crear");
        jb_CrearDependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_CrearDependenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_CrearDependencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jldep2)
                        .addGap(45, 45, 45)
                        .addComponent(cb_zonaDependencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jldep1)
                            .addComponent(jldep))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_CodigoDependencia, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jt_NombreDependencia))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jldep)
                    .addComponent(jt_CodigoDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jldep1)
                    .addComponent(jt_NombreDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jldep2)
                    .addComponent(cb_zonaDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jb_CrearDependencia)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout Jd_crearDependenciaLayout = new javax.swing.GroupLayout(Jd_crearDependencia.getContentPane());
        Jd_crearDependencia.getContentPane().setLayout(Jd_crearDependenciaLayout);
        Jd_crearDependenciaLayout.setHorizontalGroup(
            Jd_crearDependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Jd_crearDependenciaLayout.setVerticalGroup(
            Jd_crearDependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jb_EliminarDependencia.setText("Eliminar");
        jb_EliminarDependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_EliminarDependenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(cb_eliminarDempendencia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jb_EliminarDependencia)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(cb_eliminarDempendencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jb_EliminarDependencia)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout jd_eliminarDependenciaLayout = new javax.swing.GroupLayout(jd_eliminarDependencia.getContentPane());
        jd_eliminarDependencia.getContentPane().setLayout(jd_eliminarDependenciaLayout);
        jd_eliminarDependenciaLayout.setHorizontalGroup(
            jd_eliminarDependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_eliminarDependenciaLayout.setVerticalGroup(
            jd_eliminarDependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jldep3.setText("Zona");

        jldep4.setText("CodigoDependencia");

        jldep5.setText("Nombre");

        jb_BuscarDependencia.setText("Buscar");
        jb_BuscarDependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_BuscarDependenciaActionPerformed(evt);
            }
        });

        jb_ModDepencia.setText("Modificar");
        jb_ModDepencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ModDepenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jldep4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jldep3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jl_zonadependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jldep5)
                                    .addComponent(jt_idDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_BuscarDependencia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jl_codigodependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jt_ModNombreDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(3, 3, 3)))))
                        .addContainerGap(59, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_ModDepencia)
                .addGap(146, 146, 146))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_idDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_BuscarDependencia))
                .addGap(26, 26, 26)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_zonadependencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jldep3)))
                .addGap(33, 33, 33)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_codigodependencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jldep4)))
                .addGap(31, 31, 31)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jldep5)
                    .addComponent(jt_ModNombreDependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jb_ModDepencia)
                .addContainerGap())
        );

        javax.swing.GroupLayout JD_ModificarDependenciaLayout = new javax.swing.GroupLayout(JD_ModificarDependencia.getContentPane());
        JD_ModificarDependencia.getContentPane().setLayout(JD_ModificarDependenciaLayout);
        JD_ModificarDependenciaLayout.setHorizontalGroup(
            JD_ModificarDependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_ModificarDependenciaLayout.setVerticalGroup(
            JD_ModificarDependenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Sistema de Mantenimiento del Zoologico de Cordoba");

        bt_entrarPersonal.setText("Entrar");

        jLabel2.setText("Personal:");

        jLabel3.setText("Animales:");

        bt_entrarAnimales.setText("Entrar");

        jLabel4.setText("Zoologico:");

        bt_entrarZoologico.setText("Entrar");
        bt_entrarZoologico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_entrarZoologicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_entrarAnimales, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(bt_entrarZoologico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_entrarPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bt_entrarPersonal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bt_entrarAnimales))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bt_entrarZoologico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jb_VentanaZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jb_VentanaZonaActionPerformed
        this.jd_Zona.pack();
        this.jd_Zona.setResizable(false);
        this.jd_Zona.setLocationRelativeTo(this);
        this.jd_Zona.setVisible(true);
    }//GEN-LAST:event_Jb_VentanaZonaActionPerformed

    private void jb_CrearZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_CrearZonaActionPerformed
        this.jd_crearzona.pack();
        this.jd_crearzona.setResizable(false);
        this.jd_crearzona.setLocationRelativeTo(this);
        this.jd_crearzona.setVisible(true);
    }//GEN-LAST:event_jb_CrearZonaActionPerformed

    private void jb_modificarZonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarZonasActionPerformed
        this.jd_modifcarzona.pack();
        this.jd_modifcarzona.setResizable(false);
        this.jd_modifcarzona.setLocationRelativeTo(this);
        this.jd_modifcarzona.setVisible(true);
    }//GEN-LAST:event_jb_modificarZonasActionPerformed

    private void jb_eliminarzonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarzonasActionPerformed
        cb_EliminarZona.removeAllItems();
        ComboBoxModel model = this.cb_EliminarZona.getModel();
        FindIterable<Document> iterDoc = db.getCollection("Zonas").find();
        int i = 1;
        for (Document doc : iterDoc) {
            this.cb_EliminarZona.addItem(doc.get("CodigoZona").toString());
            i++;
        }
        this.jd_eliminarZona.pack();
        this.jd_eliminarZona.setResizable(false);
        this.jd_eliminarZona.setLocationRelativeTo(this);
        this.jd_eliminarZona.setVisible(true);
    }//GEN-LAST:event_jb_eliminarzonasActionPerformed

    private void jb_crearZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearZActionPerformed
        long codigoZona = Integer.parseInt(jt_codigozona.getText());
        String nombre = jt_nombrezona.getText();
        try {
            Document doc = new Document();
            doc.append("CodigoZona", codigoZona);
            doc.append("Nombre", nombre);
            db.getCollection("Zonas").insertOne(doc);
            JOptionPane.showMessageDialog(this.jd_crearzona, "Creada Exitosamente");
            jt_nombrezona.setText("");
            jt_codigozona.setText("");
            jd_crearzona.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_crearZActionPerformed

    private void bt_entrarZoologicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarZoologicoActionPerformed
        this.VentanaZoologico.pack();
        this.VentanaZoologico.setResizable(false);
        this.VentanaZoologico.setLocationRelativeTo(this);
        this.VentanaZoologico.setVisible(true);
    }//GEN-LAST:event_bt_entrarZoologicoActionPerformed

    private void jb_eliminarZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarZonaActionPerformed
        int codZona = Integer.parseInt(cb_EliminarZona.getSelectedItem().toString());
        int opcion;
        try {
            opcion = JOptionPane.showConfirmDialog(this.jd_eliminarZona, "¿Desea Borrarlo?", "Borrar", YES_NO_OPTION);
            if (opcion == 0) {
                db.getCollection("Zonas").deleteOne(Filters.eq("CodigoZona", codZona));
                JOptionPane.showMessageDialog(this.jd_eliminarZona, "Eliminado!");
            }
        } catch (Exception e) {
        }
        jd_eliminarZona.setVisible(false);
    }//GEN-LAST:event_jb_eliminarZonaActionPerformed

    private void jt_BuscarModificarZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_BuscarModificarZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_BuscarModificarZActionPerformed

    private void jb_buscarModificarZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarModificarZActionPerformed
        int CodZona;
        try {
            CodZona = Integer.parseInt(this.jt_BuscarModificarZ.getText());
            BasicDBObject query = new BasicDBObject();
            query.put("CodigoZona", CodZona);
            Document doc = db.getCollection("Zonas").find(query).first();
            jt_nombreModificarZona.setText((String) doc.get("Nombre"));
            jl_idModificarZ.setText(CodZona + "");
            JOptionPane.showMessageDialog(this.jd_eliminarZona, "Encontrado!");
            jt_nombreModificarZona.setEnabled(true);
            jb_ModificarZona.setEnabled(true);
            jt_BuscarModificarZ.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jb_buscarModificarZActionPerformed

    private void jb_ModificarZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ModificarZonaActionPerformed
        String nombre = jt_nombreModificarZona.getText();
        int CodZona;
        try {
            CodZona = Integer.parseInt(this.jl_idModificarZ.getText());
            db.getCollection("Zonas").updateOne(Filters.eq("CodigoZona", CodZona), Updates.set("Nombre", nombre));
            JOptionPane.showMessageDialog(this.jd_crearzona, "Modificado Con Exito");
            jt_nombreModificarZona.setEnabled(false);
            jb_ModificarZona.setEnabled(false);
            jt_nombreModificarZona.setText("");
            jl_idModificarZ.setText("");
            jd_modifcarzona.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_ModificarZonaActionPerformed

    private void jb_ModificarHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ModificarHabitatActionPerformed
        String nombre = jt_ModNombreHabitat.getText();
        int CodZona;
        try {
            CodZona = Integer.parseInt(this.jl_codigohabitat.getText());
            db.getCollection("Habitat").updateOne(Filters.eq("CodigoHabitat", CodZona), Updates.set("Nombre", nombre));
            JOptionPane.showMessageDialog(this.jd_ModificarHabitat, "Modificado Con Exito");
            jt_ModNombreHabitat.setEnabled(false);
            jb_ModificarHabitat.setEnabled(false);
            jt_ModNombreHabitat.setText("");
            jl_codigohabitat.setText("");
            jl_zonahabitat.setText("");
            jd_ModificarHabitat.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_ModificarHabitatActionPerformed

    private void jb_buscarhabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarhabitatActionPerformed
        int CodZona;
        try {
            CodZona = Integer.parseInt(jt_BuscarModHabitat.getText());
            BasicDBObject query = new BasicDBObject();
            query.put("CodigoHabitat", CodZona);
            Document doc = db.getCollection("Habitat").find(query).first();
            jt_ModNombreHabitat.setText((String) doc.get("Nombre"));
            jl_codigohabitat.setText(CodZona + "");
            jl_zonahabitat.setText(doc.get("CodigoZona") + "");
            JOptionPane.showMessageDialog(this.jd_eliminarZona, "Encontrado!");
            jt_ModNombreHabitat.setEnabled(true);
            jb_ModificarHabitat.setEnabled(true);
            jt_BuscarModHabitat.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_buscarhabitatActionPerformed

    private void jb_crearhabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearhabitatActionPerformed
        long codigoZona = Integer.parseInt(jt_CodigoHabitat.getText());
        String nombre = Jt_NombreHabitat.getText();
        long codigozona = Integer.parseInt(cb_zonacrearhabitat.getSelectedItem().toString());
        try {
            Document doc = new Document();
            doc.append("CodigoHabitat", codigoZona);
            doc.append("CodigoZona", codigozona);
            doc.append("Nombre", nombre);
            db.getCollection("Habitat").insertOne(doc);
            JOptionPane.showMessageDialog(this.jd_crearzona, "Creada Exitosamente");
            jt_CodigoHabitat.setText("");
            Jt_NombreHabitat.setText("");
            Jd_CrearHabitat.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_crearhabitatActionPerformed

    private void jd_VentanaCrearHbitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jd_VentanaCrearHbitatActionPerformed
        cb_zonacrearhabitat.removeAllItems();
        ComboBoxModel model = this.cb_zonacrearhabitat.getModel();
        FindIterable<Document> iterDoc = db.getCollection("Zonas").find();
        int i = 1;
        for (Document doc : iterDoc) {
            this.cb_zonacrearhabitat.addItem(doc.get("CodigoZona").toString());
            i++;
        }
        this.Jd_CrearHabitat.pack();
        this.Jd_CrearHabitat.setResizable(false);
        this.Jd_CrearHabitat.setLocationRelativeTo(this);
        this.Jd_CrearHabitat.setVisible(true);
    }//GEN-LAST:event_jd_VentanaCrearHbitatActionPerformed

    private void jb_VentanaDependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_VentanaDependenciaActionPerformed
        this.JD_Dependencias.pack();
        this.JD_Dependencias.setResizable(false);
        this.JD_Dependencias.setLocationRelativeTo(this);
        this.JD_Dependencias.setVisible(true);
    }//GEN-LAST:event_jb_VentanaDependenciaActionPerformed

    private void jb_VentanaHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_VentanaHabitatActionPerformed
        this.jd_Habitats.pack();
        this.jd_Habitats.setResizable(false);
        this.jd_Habitats.setLocationRelativeTo(this);
        this.jd_Habitats.setVisible(true);
    }//GEN-LAST:event_jb_VentanaHabitatActionPerformed

    private void jb_VentanaModificarHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_VentanaModificarHabitatActionPerformed
        this.jd_ModificarHabitat.pack();
        this.jd_ModificarHabitat.setResizable(false);
        this.jd_ModificarHabitat.setLocationRelativeTo(this);
        this.jd_ModificarHabitat.setVisible(true);
    }//GEN-LAST:event_jb_VentanaModificarHabitatActionPerformed

    private void JB_VentatnaEliminarHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_VentatnaEliminarHabitatActionPerformed
        cb_eliminarHabitat.removeAllItems();
        ComboBoxModel model = this.cb_eliminarHabitat.getModel();
        FindIterable<Document> iterDoc = db.getCollection("Habitat").find();
        int i = 1;
        for (Document doc : iterDoc) {
            this.cb_eliminarHabitat.addItem(doc.get("CodigoHabitat").toString());
            i++;
        }
        this.jd_EliminarHabitat.pack();
        this.jd_EliminarHabitat.setResizable(false);
        this.jd_EliminarHabitat.setLocationRelativeTo(this);
        this.jd_EliminarHabitat.setVisible(true);
    }//GEN-LAST:event_JB_VentatnaEliminarHabitatActionPerformed

    private void jb_eliminarHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarHabitatActionPerformed
        int codZona = Integer.parseInt(cb_eliminarHabitat.getSelectedItem().toString());
        int opcion;
        try {
            opcion = JOptionPane.showConfirmDialog(this.jd_EliminarHabitat, "¿Desea Borrarlo?", "Borrar", YES_NO_OPTION);
            if (opcion == 0) {
                db.getCollection("Habitat").deleteOne(Filters.eq("CodigoHabitat", codZona));
                JOptionPane.showMessageDialog(this.jd_EliminarHabitat, "Eliminado!");
            }
        } catch (Exception e) {
        }
        jd_EliminarHabitat.setVisible(false);
    }//GEN-LAST:event_jb_eliminarHabitatActionPerformed

    private void jb_CrearDependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_CrearDependenciaActionPerformed
        long codigoZona = Integer.parseInt(jt_CodigoDependencia.getText());
        String nombre = jt_NombreDependencia.getText();
        long codigozona = Integer.parseInt(cb_zonaDependencia.getSelectedItem().toString());
        try {
            Document doc = new Document();
            doc.append("CodigoDependencia", codigoZona);
            doc.append("CodigoZona", codigozona);
            doc.append("NombreDependencia", nombre);
            db.getCollection("Dependencias").insertOne(doc);
            JOptionPane.showMessageDialog(this.jd_crearzona, "Creada Exitosamente");
            jt_CodigoDependencia.setText("");
            jt_NombreDependencia.setText("");
            Jd_crearDependencia.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_CrearDependenciaActionPerformed

    private void jb_EliminarDependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_EliminarDependenciaActionPerformed
        int codZona = Integer.parseInt(cb_eliminarDempendencia.getSelectedItem().toString());
        int opcion;
        try {
            opcion = JOptionPane.showConfirmDialog(this.jd_eliminarDependencia, "¿Desea Borrarlo?", "Borrar", YES_NO_OPTION);
            if (opcion == 0) {
                db.getCollection("Dependencias").deleteOne(Filters.eq("CodigoDependencia", codZona));
                JOptionPane.showMessageDialog(this.jd_EliminarHabitat, "Eliminado!");
            }
        } catch (Exception e) {
        }
        jd_eliminarDependencia.setVisible(false);
    }//GEN-LAST:event_jb_EliminarDependenciaActionPerformed

    private void jb_BuscarDependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_BuscarDependenciaActionPerformed
        int CodZona;
        try {
            CodZona = Integer.parseInt(jt_idDependencia.getText());
            BasicDBObject query = new BasicDBObject();
            query.put("CodigoDependencia", CodZona);
            Document doc = db.getCollection("Dependencias").find(query).first();
            jt_ModNombreDependencia.setText((String) doc.get("NombreDependencia"));
            jl_codigodependencia.setText(CodZona + "");
            jl_zonadependencia.setText(doc.get("CodigoZona") + "");
            JOptionPane.showMessageDialog(this.jd_eliminarZona, "Encontrado!");
            jt_ModNombreDependencia.setEnabled(true);
            jb_ModDepencia.setEnabled(true);
            jt_idDependencia.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_BuscarDependenciaActionPerformed

    private void jb_ModDepenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ModDepenciaActionPerformed
        String nombre = jt_ModNombreDependencia.getText();
        int CodZona;
        try {
            CodZona = Integer.parseInt(this.jl_codigodependencia.getText());
            db.getCollection("Dependencias").updateOne(Filters.eq("CodigoDependencia", CodZona), Updates.set("NombreDependencia", nombre));
            JOptionPane.showMessageDialog(this.jd_ModificarHabitat, "Modificado Con Exito");
            jt_ModNombreDependencia.setEnabled(false);
            jb_ModDepencia.setEnabled(false);
            jt_ModNombreDependencia.setText("");
            jl_zonadependencia.setText("");
            jl_codigodependencia.setText("");
            JD_ModificarDependencia.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jb_ModDepenciaActionPerformed

    private void jb_VtcrearDependenicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_VtcrearDependenicaActionPerformed
        cb_zonaDependencia.removeAllItems();
        ComboBoxModel model = this.cb_zonaDependencia.getModel();
        FindIterable<Document> iterDoc = db.getCollection("Zonas").find();
        int i = 1;
        for (Document doc : iterDoc) {
            this.cb_zonaDependencia.addItem(doc.get("CodigoZona").toString());
            i++;
        }
        this.Jd_crearDependencia.pack();
        this.Jd_crearDependencia.setResizable(false);
        this.Jd_crearDependencia.setLocationRelativeTo(this);
        this.Jd_crearDependencia.setVisible(true);
    }//GEN-LAST:event_jb_VtcrearDependenicaActionPerformed

    private void jb_VTModDependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_VTModDependenciaActionPerformed
        this.JD_ModificarDependencia.pack();
        this.JD_ModificarDependencia.setResizable(false);
        this.JD_ModificarDependencia.setLocationRelativeTo(this);
        this.JD_ModificarDependencia.setVisible(true);
    }//GEN-LAST:event_jb_VTModDependenciaActionPerformed

    private void jb_VTEliminarDependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_VTEliminarDependenciaActionPerformed
        cb_eliminarDempendencia.removeAllItems();
        ComboBoxModel model = this.cb_eliminarDempendencia.getModel();
        FindIterable<Document> iterDoc = db.getCollection("Dependencias").find();
        int i = 1;
        for (Document doc : iterDoc) {
            this.cb_eliminarDempendencia.addItem(doc.get("CodigoDependencia").toString());
            i++;
        }
        this.jd_eliminarDependencia.pack();
        this.jd_eliminarDependencia.setResizable(false);
        this.jd_eliminarDependencia.setLocationRelativeTo(this);
        this.jd_eliminarDependencia.setVisible(true);
    }//GEN-LAST:event_jb_VTEliminarDependenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_VentatnaEliminarHabitat;
    private javax.swing.JDialog JD_Dependencias;
    private javax.swing.JDialog JD_ModificarDependencia;
    private javax.swing.JButton Jb_VentanaZona;
    private javax.swing.JDialog Jd_CrearHabitat;
    private javax.swing.JDialog Jd_crearDependencia;
    private javax.swing.JTextField Jt_NombreHabitat;
    private javax.swing.JDialog VentanaZoologico;
    private javax.swing.JButton bt_entrarAnimales;
    private javax.swing.JButton bt_entrarPersonal;
    private javax.swing.JButton bt_entrarZoologico;
    private javax.swing.JComboBox<String> cb_EliminarZona;
    private javax.swing.JComboBox<String> cb_eliminarDempendencia;
    private javax.swing.JComboBox<String> cb_eliminarHabitat;
    private javax.swing.JComboBox<String> cb_zonaDependencia;
    private javax.swing.JComboBox<String> cb_zonacrearhabitat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jb_BuscarDependencia;
    private javax.swing.JButton jb_CrearDependencia;
    private javax.swing.JButton jb_CrearZona;
    private javax.swing.JButton jb_EliminarDependencia;
    private javax.swing.JButton jb_ModDepencia;
    private javax.swing.JButton jb_ModificarHabitat;
    private javax.swing.JButton jb_ModificarZona;
    private javax.swing.JButton jb_VTEliminarDependencia;
    private javax.swing.JButton jb_VTModDependencia;
    private javax.swing.JButton jb_VentanaDependencia;
    private javax.swing.JButton jb_VentanaHabitat;
    private javax.swing.JButton jb_VentanaModificarHabitat;
    private javax.swing.JButton jb_VtcrearDependenica;
    private javax.swing.JButton jb_buscarModificarZ;
    private javax.swing.JButton jb_buscarhabitat;
    private javax.swing.JButton jb_crearZ;
    private javax.swing.JButton jb_crearhabitat;
    private javax.swing.JButton jb_eliminarHabitat;
    private javax.swing.JButton jb_eliminarZona;
    private javax.swing.JButton jb_eliminarzonas;
    private javax.swing.JButton jb_modificarZonas;
    private javax.swing.JDialog jd_EliminarHabitat;
    private javax.swing.JDialog jd_Habitats;
    private javax.swing.JDialog jd_ModificarHabitat;
    private javax.swing.JButton jd_VentanaCrearHbitat;
    private javax.swing.JDialog jd_Zona;
    private javax.swing.JDialog jd_crearzona;
    private javax.swing.JDialog jd_eliminarDependencia;
    private javax.swing.JDialog jd_eliminarZona;
    private javax.swing.JDialog jd_modifcarzona;
    private javax.swing.JLabel jl_codigodependencia;
    private javax.swing.JLabel jl_codigohabitat;
    private javax.swing.JLabel jl_idModificarZ;
    private javax.swing.JLabel jl_zonadependencia;
    private javax.swing.JLabel jl_zonahabitat;
    private javax.swing.JLabel jldep;
    private javax.swing.JLabel jldep1;
    private javax.swing.JLabel jldep2;
    private javax.swing.JLabel jldep3;
    private javax.swing.JLabel jldep4;
    private javax.swing.JLabel jldep5;
    private javax.swing.JLabel jlzona;
    private javax.swing.JLabel jlzona1;
    private javax.swing.JLabel jlzona10;
    private javax.swing.JLabel jlzona11;
    private javax.swing.JLabel jlzona12;
    private javax.swing.JLabel jlzona13;
    private javax.swing.JLabel jlzona3;
    private javax.swing.JLabel jlzona5;
    private javax.swing.JLabel jlzona8;
    private javax.swing.JLabel jlzona9;
    private javax.swing.JTextField jt_BuscarModHabitat;
    private javax.swing.JTextField jt_BuscarModificarZ;
    private javax.swing.JTextField jt_CodigoDependencia;
    private javax.swing.JTextField jt_CodigoHabitat;
    private javax.swing.JTextField jt_ModNombreDependencia;
    private javax.swing.JTextField jt_ModNombreHabitat;
    private javax.swing.JTextField jt_NombreDependencia;
    private javax.swing.JTextField jt_codigozona;
    private javax.swing.JTextField jt_idDependencia;
    private javax.swing.JTextField jt_nombreModificarZona;
    private javax.swing.JTextField jt_nombrezona;
    // End of variables declaration//GEN-END:variables
}
